#pragma once
#include "NativeGameplayTags.h"

TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Area_Area1);
TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Area_Area2);
TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Area_Area3);

