#pragma once
#include "NativeGameplayTags.h"

namespace GamePlayTags
{
	namespace AreaTag
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Area_Area1);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Area_Area2);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Area_Area3);
	}
	
	namespace PlayerRole
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Civilian);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Infected);
	}
	
	namespace CivilianState
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead);
	}
	
	namespace CivilianAbility
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Secondary);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shoot);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload);
	}
	
	namespace InfectedState
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Morphing);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead);
	}
	
	namespace InfectedAbility
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Secondary);
	}
	
	namespace Data
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HealAmount);
	}
	
	namespace Effect
	{
		TEAM10_4PROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role);
	}
}
